apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: hello-serving
  annotations:
    scenarios.ai.sap.com/description: "Simple Hello World Serving"
    scenarios.ai.sap.com/name: "hello-world"
    executables.ai.sap.com/description: "Serving executable"
    executables.ai.sap.com/name: "serving"
  labels:
    scenarios.ai.sap.com/id: "hello-world"
    ai.sap.com/version: "1.0"
spec:
  predictor:
    imagePullSecrets:
      - name: default-docker-registry
    minReplicas: 1
    maxReplicas: 1
    containers:
    - name: kserve-container
      image: sapse/sklearn-iris:latest
      ports:
      - containerPort: 9001
        protocol: TCP
